### ISSUE TITLE
Fix some typos and case inconsistencies

### ISSUE THREAD

**Issue by jbpaux** [AsBuiltReport/AsBuiltReport.Microsoft.DHCP#18]
### Bug description

The report has some typos in it (authetication for example) and the case of some abbreviation is not consistent across the report.

### Command-line input

New-AsBuiltReportConfig -Report Microsoft.DHCP -FolderPath <User specified folder> -Filename <Optional>

### Steps to reproduce

1. Execute the command
2. View report

### Expected behaviour

No typos

### Operating System

not important

### PowerShell Version

not important

### PowerShell Modules

not important

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.DHCP/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
I know several languages but English is definitely not my area of expertise. If you find any paraphrase or text that doesn't make sense please let me know!

Thanks!
